{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretRefName | quote }}
    server: {{ .Values.clusterIssuer.server | quote }}
    solvers:
{{- if eq .Values.clusterIssuer.solver.type "dns01" }}
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.clusterIssuer.solver.dns01.cloudflare.apiTokenSecretRef.name | quote }}
              key: {{ .Values.clusterIssuer.solver.dns01.cloudflare.apiTokenSecretRef.key | quote }}
{{- else if eq .Values.clusterIssuer.solver.type "http01" }}
      - http01:
          ingress:
            class: {{ .Values.clusterIssuer.solver.http01.ingressClass | quote }}
{{- else }}
      # No valid solver configured
      - http01:
          ingress:
            class: {{ .Values.clusterIssuer.solver.http01.ingressClass | quote }}
{{- end }}
{{- end }}
