apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-operator-webhook-server-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: cloudflare-operator-webhook-server-cert
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - cloudflare-operator-webhook-service.{{ .Release.Namespace }}.svc
  - cloudflare-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
