apiVersion: v1
kind: Service
metadata:
  name: cloudflare-operator-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: webhook-server
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "cloudflare-operator.selectorLabels" . | nindent 4 }}
